config/routes.rb
Rails.application.routes.draw do

  resources :notes

  get 'reports/index'

  match 'admin/meetups/add_and_attend_meetup/:id', to: 'meetups#add_and_attend_meetup', via: 'patch'
  match 'admin/meetups/attend_meetup', to: 'meetups#attend_meetup', via: 'patch'

  scope :admin do
    resources :meetups
    resources :users
    get "reports", controller: 'reports', action: 'index'
  end

  root 'meetups#index'

end

app/models/meetup.rb
class Meetup < ActiveRecord::Base

  extend FriendlyId

  # https://robots.thoughtbot.com/accepts-nested-attributes-for-with-has-many-through
  has_many :meetup_attendees, inverse_of: :meetup
  has_many :attendees, through: :meetup_attendees, source: :attendee

  accepts_nested_attributes_for :meetup_attendees

  friendly_id :date, use: :slugged

  # TODO: should we use scopes? to privde the ability to look up any language
  # after leading the meetup for almost a year, it's pretty clear that the
  # attendees are an international crowd and it's not either Japanese or English
  # for native language. It would be advisable to create a column called,
  # native_japanese and make it a boolean. When they enter their name and language,
  # if they enter anything but Japanese it will mark native_japanese to false.

  # scope :language, ->(language) {
  #   where(native_language: language)
  # }

  def non_japanese_attendees
    attendees.where.not(native_language: 'Japanese')
  end

  def english_attendees
    lookup native_language: "English"
  end

  def japanese_attendees
    lookup native_language: "Japanese"
  end

  private
  def lookup(**options)
    attendees.where(options)
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController

  before_action :set_meetup, except: [:index, :new, :create]

  def index
    @meetups = Meetup.all.order(date: :desc)
  end

  def new
    @meetup = Meetup.new
  end

  def edit
  end

  # action to create a meetup. Vanilla CRUD
  def create
    @meetup = Meetup.new(meetup_params)

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to @meetup, notice: 'Meetup was successfully created.' }
        format.json { render :show, status: :created, location: @meetup }
      else
        format.html { render :new }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  # adds and attendee to a meetup
  def attend_meetup
    if @meetup.update(meetup_params)
      flash[:success] = 'Marked Attending'
      redirect_to @meetup
    else
      flash[:danger] = @meetup.errors.full_messages.join(",")
      redirect_to @meetup
    end
  end

  # creates the incoming user and adds them to the meetup it was submitted from
  def add_and_attend_meetup
    user = User.new(name: params[:user][:name],
      email: params[:user][:email],
      native_language: params[:user][:native_language])

    respond_to do |format|
      if user.save
        @meetup.meetup_attendees.create(user_id: user.id)

        flash[:success] = "#{user.name} marked as present."
        format.html { redirect_to @meetup }
        format.json { render :show, status: :created, location: @meetup}
      else
        flash[:danger] = "Problem creating user: #{user.errors.full_messages.join(", ")}"
        format.html { redirect_to @meetup }
        format.json { render json: user.errors, status: :unprocessable_entity }
      end
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meetup
    @meetup = Meetup.friendly.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meetup_params
    params.require(:meetup).permit(:date, :meetup_attendees_attributes => [:user_id])
  end
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/meetups/index.html.erb
<%= provide(:title, "Meetups") %>
<div class="container">
  <h1>Meetups</h1>
  <%= link_to "New Meetup", new_meetup_path, class: "btn btn-primary" %>
  <hr />
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Japanese</th>
        <th>English</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <% @meetups.each do | meetup | %>
      <tr>
        <td><%= link_to meetup.date, meetup %></td>
        <td><%= meetup.japanese_attendees.count %></td>
        <td><%= meetup.english_attendees.count %></td>
        <td><%= meetup.attendees.count %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/meetups/new.html.erb
<div class="container">
  <h1>New Meetup</div>
  <div class="row">
    <div class="col-md-12">
      <div style="padding:20px;">
        <%= simple_form_for @meetup do | f | %>
          <div class="row">
            <div class="col-md-4">
              <%= f.input :date %>
            </div>
          </div>
          <%= f.submit "Save", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/meetups/show.html.erb
<div class="container">
  <h1><%= @meetup.date %> <% if @meetup.attendees.count > 0 %><small>(<%= @meetup.attendees.count %>)</small><% end %></h1>
  <hr />
  <div class="row">
    <div class="col-md-6">
      <h4>Breakdown</h4>
      <% if @meetup.attendees.count > 0 %>
        <% data = [
            { value: @meetup.japanese_attendees.count, color:"#F7464A", highlight: "#FF5A5E", label: "Japanese"},
            { value: @meetup.non_japanese_attendees.count, color:"#46BFBD", highlight: "#5AD3D1", label: "English"}
            ] %>
        <%= pie_chart(data,
          animation: false,
          responsive: true,
          generateLegend: true,
          legendTemplate: render("layouts/legend") ) %>
      <% else %>
        A pie chart containing a break down of Japanese native and non native
        speakers will appear after someone attends the meetup.
      <% end %>
    </div>
    <div class="col-md-6">
      <h4>Roll Sheet</h4>
      <% if @meetup.attendees.count > 0 %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Native Language</th>
          </tr>
        </thead>
        <tbody>
          <% @meetup.attendees.each do | attendee | %>
          <tr>
            <td><%= attendee.name %></td>
            <td><%= attendee.native_language %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>

      <ul id="sign_in_tabs" class="nav nav-tabs">
        <li id="sign_in_tab" role="presentation" class="active"><a href="#">Check In</a></li>
        <li id="new_attendee_tab" role="presentation"><a href="#">Sign Up</a></li>
      </ul>
      <br />

      <div id="sign_in" class="panel panel-default" style="padding:20px;">
        <%= render "shared/sign_in", meetup: @meetup %>
      </div>

      <div id="new_attendee" class="panel panel-default" style="padding:20px;display:none;">
        <%= render "shared/new_attendee", meetup: @meetup %>
      </div>

    </div>
  </div>
</div>

<script>
  $('ul#sign_in_tabs li').click(function(e) {
    e.preventDefault();
    switch(this.id) {
      case "new_attendee_tab":
        $("#sign_in_tab").removeClass("active");
        $("#new_attendee_tab").addClass("active");
        $("#new_attendee").show();
        $("#sign_in").hide();
        break;
      case "sign_in_tab":
        $("#new_attendee_tab").removeClass("active");
        $("#sign_in_tab").addClass("active");
        $("#sign_in").show();
        $("#new_attendee").hide();
        break;
      default:
    }
  });
</script>