config/routes.rb
Rails.application.routes.draw do

  resources :notes

  get 'reports/index'

  match 'admin/meetups/add_and_attend_meetup/:id', to: 'meetups#add_and_attend_meetup', via: 'patch'
  match 'admin/meetups/attend_meetup', to: 'meetups#attend_meetup', via: 'patch'

  scope :admin do
    resources :meetups
    resources :users
    get "reports", controller: 'reports', action: 'index'
  end

  root 'meetups#index'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Kaiwa Club", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse" id="navbarCollapse">
        <ul class="nav navbar-nav navbar-right">
        <li>
            <%= link_to "Notes", notes_path %>
        </li>
         <li>
           <%= link_to "Meetups", meetups_path %>
         </li>
         <li>
           <%= link_to "Reports", reports_path %>
         </li>
       </ul>
    </div>
  </div>
</nav>

app/views/layouts/_line_legend.html.erb
<ul class=\"legend\">
  <%% for (var i=0; i<datasets.length; i++){%>
    <li>
      <span style=\"background-color:<%%=datasets[i].strokeColor%>\"></span>
      <%%if(datasets[i].label){%><%%=datasets[i].label%><%%}%>
    </li>
  <%%}%>
</ul>

app/views/layouts/_multi_tooltip.html.erb
<%%= datasetLabel %>: <%%= value %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
  <% flash.each do | message_type, message | %>
    <% next if message_type == "modal" %>
    <div class="alert alert-<%= message_type %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= message %>
    </div>
  <% end %>
  </div>  
  <%= yield %>
</body>
</html>